### ISSUE TITLE
Unresponsive components (in the JS thread)

### ISSUE THREAD

**Issue by alanz** [staltz/mmmmm-mobile#15]
**Steps to reproduce the bug:**

install v0.0.9 alpha over an existing v0.0.9 alpha install

**Expected behavior:**

UI responds: can like, post message, select profile

**Actual behavior:**

The only UI events that seem to be handled are scrolling up and down the feed, and swiping left/right to see the other columns.

Pressing for a long time in the new post area eventually shows a "paste" option, which does paste the clipboard. But it is impossible to edit the paste. Not even a keyboard shows up.

**Technical details**

- MMMMM app version: v0.0.9-alpha
- Device/phone model: OnePlus5
- Android OS version: 7.1.1, OxygenOs 4.5.14

**Comment by staltz** [comment]
Were you syncing while you were doing this, or not?

**Comment by alanz** [comment]
Syncing had completed. In that it was showing recent info. I can wait longer and see if anything changes.

**Comment by alanz** [comment]
It was close to synced-up before I installed the new one

**Comment by alanz** [comment]
I erased the earlier data and restarted, and it now behaves.

I guess its just alpha software, slowly improving.

**Comment by staltz** [comment]
I'm asking because I found a "flickering" issue related to the text input box, I'm curious if it's syncing related or just pure UI stuff. Anyways, thanks for reporting, it's important. I'll assume this issue was the flickering bug.

**Comment by alanz** [comment]
The "flickering" in the text input box (for me) is a text input cursor appearing when tapping the area and then immediately disappearing.

But the other UI elements that were not working (prior to deleting data) were all of the ones in the blue area above the text input area.

So could not enter for search, select profile, or change tabs via the icons.

**Comment by staltz** [comment]
Okay, that's different, I'll rename this issue.

**Comment by alanz** [comment]
And I think it is related to syncing, because it went into that state again, while syncing the backlog, but came out of it again quite quickly. 

Once fully synced, it is responsive again.

**Comment by staltz** [comment]
Anyway it's important to fix, because in principle syncing is done in the background, in a completely different process than the UI app.

**Comment by staltz** [comment]
I think I discovered what this is. The top tab buttons react to user events on the JS thread while the scrolling view (for the feed) is on the native UI thread. The former is unresponsive but the latter is always responsive. This means there is too much work happening on the JS thread. That's a sign. I need to profile the performance and see if most of that work can be moved to the background JS process or the native UI thread.

**Comment by staltz** [comment]
I think with 0.0.12, this is solved. If any other similar problems arise, we can open other issues
