### ISSUE TITLE
adb install mmmm.apk failed

### ISSUE THREAD

**Issue by dominictarr** [staltz/mmmmm-mobile#2]
trying to install the apk I get this error

https://stackoverflow.com/questions/19070816/failure-install-failed-invalid-apk

not sure what it is but making this issue to track the problem.

**Comment by dominictarr** [comment]
oh, I think the problem is that my android is armv7 which is 32 bit but this is a 64 bit linux, because I got the same problem with https://github.com/mafintosh/node-on-android/releases/tag/pre-alpha

**Comment by staltz** [comment]
Supporting 32 bit is very important because we'll target low end devices, but I need to either get hold of such device or you should try compiling the apk. I can buy a cheap device but maybe that'll take a while.

**Comment by dominictarr** [comment]
I'll getting everything set up to build today.

**Comment by staltz** [comment]
I got an armv7 android phone and I'll focus on getting it working with react-native-node.

**Comment by aschrijver** [comment]
Hmm strange, I have tested the `react-native-node` example on ARM7 and installed this app successfully (but did not testdrive it to see if it worked). Both on emulator and real Samsung A3.

(But currently I'm using [react-native-node on top of J2V8](https://github.com/staltz/react-native-node/issues/5#issuecomment-323049897))

**Comment by dominictarr** [comment]
at one point I did get the app started, but it dumped an error about node process exiting into the ADB logs, the app appeared to be running, but it didn't have the backend!

**Comment by staltz** [comment]
My Android armv7 is a bit too old, it needs SDK v17, so I can't even get the apk installed to begin with. But I'll make it a goal to have it installed on quite old phones too.

**Comment by staltz** [comment]
As of MMMMM v0.0.6+, it has been working on an armv7l device normally, so this issue is 'cant reproduce'.
