### ISSUE TITLE
Are private messages testable? 

### ISSUE THREAD

**Issue by mrspiderbrain** [staltz/mmmmm-mobile#25]
Installed alpha 0.0.10 apk on LineageOS v14 on a samsung note3. Runs stable. 
Have managed a public post OK. 
Channel added OK on public post, but doesn't render as a channel on mmmmm UI. 
Channel renders successfully on patchwork. 
Are private messages supported? I am trying to "befriend" my other device, but not sure if A) it is supported and B) what the UI steps are to do that.
Managed to change my username and bio OK.

**Comment by staltz** [comment]
Hi! Thanks for the feedback on what works and what doesn't yet. I actually didn't know adding a channel to a public post worked. :)

Rendering channels and private messages are things explicitly on the roadmap and not yet done, this project is still in alpha.

Keep following the version releases for updates. :)
