### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by rmello4d** [staltz/mmmmm-mobile#3]
I have an error on the emulator saying:

Body:
{"from":":/Users/projectr/R/mmmmm-mobile/index.android.je", "to":"./lib/main", "message": "Unable to resolve module '.lib/main' from /Users/projectr/R/mmmmm-mobile/index.android.js': could not resolve '/Users/projectr/R/mmmmm-mobile/lib/main as file nor as a folder.... 

Indeed there is no folder lib ... What am I doing wrong ? Is the folder lib installed via something else ?

**Comment by staltz** [comment]
Hi @rmello4d, you would need to `npm run lib` to generate that.

However, you should be just using `npm start` since it will also run the lib compilation.
