### ISSUE TITLE
Crashing shortly after startup on

### ISSUE THREAD

**Issue by soggypretzels** [staltz/mmmmm-mobile#4]
On version 0.0.2 and 0.0.3 mmmmm crashes a few seconds after startup on a Nexus 6P and Pixel XL (both ARM64 devices) running Android 7.1.2. After opening the app, the feed would start to populate for a second, showing posts scrolling past and then would crash to the home screen. After upgrading the Pixel to  Android 8.0.0 the app no longer crashes. This issue did not seem to be present in version 0.0.1.

**Comment by staltz** [comment]
Can you try with v0.0.4 or is it too late now that you have installed Android v8.0? FYI I'm not testing MMMMM with Android 8.0 on any of my devices, I use older Android.

**Comment by staltz** [comment]
(Closing unless confirmed to still be an issue)
