### ISSUE TITLE
Migrate to nodejs-mobile

### ISSUE THREAD

**Issue by staltz** [staltz/mmmmm-mobile#44]
Replace `react-native-node` with `nodejs-mobile`. This is currently being done by Luandro, see the fork https://github.com/luandro/mmmmm-mobile

**Comment by luandro** [comment]
Let me know if you think we're ready for a PR @staltz. There's a hack [here](https://github.com/luandro/mmmmm-mobile/blob/master/src/ssb/defaults.ts) where I had to hard code the path instead of finding it with `path` module. Other then that, I think we're good to go.

**Comment by staltz** [comment]
Ready for a PR! I think we can solve that hard coded path somehow in the PR with an additional commit
