### ISSUE TITLE
0.0.4 installed fine on cyanogenmod 13.0-20160820

### ISSUE THREAD

**Issue by mrspiderbrain** [staltz/mmmmm-mobile#5]
A few questions
1. The menu button doesn't do anything. Should it?
2. How do I set up an identity, avatar, etc?
3. Is there a way of importing a private key from another device to have a consistent identity across devices? I have patchwork on windows working already.

**Comment by staltz** [comment]
Hi @mrspiderbrain! Good that the app installed correctly on your phone. Could you tell what device you used? I want to start gathering feedback on supported devices. Particularly, I'm interested if the arch was armv7 or arm64.

> The menu button doesn't do anything. Should it?

Doesn't do anything yet.

> How do I set up an identity, avatar, etc?

Not yet possible

> Is there a way of importing a private key from another device to have a consistent identity across devices? I have patchwork on windows working already.

No it's not possible and we don't plan to make it possible. Instead, I'm planning to implement the `sameAs` (see thread `%uB7DTsgCgOgH46vKrlzNQTP0DuLcIzIVOXy0ukIWwaE=.sha256`) proposal.

- - -

You can see what features will be implemented next in this TODO file https://github.com/staltz/mmmmm-mobile/blob/master/TODO.md which I follow rigorously.

**Comment by bashrc** [comment]
I've also tested it on armv7 and it seems to work ok. Some missing features no doubt, but it's early development.

**Comment by mrspiderbrain** [comment]
I installed it on a samsung S4. 

I don't understand the link to the sameAs thread?

**Comment by staltz** [comment]
@mrspiderbrain it's an SSB link, if you copy paste it in some SSB client (e.g. patchwork) search field, it will take you to the discussion thread. Alternatively, my pub server can serve that content: http://ssb.staltz.com/view/%25uB7DTsgCgOgH46vKrlzNQTP0DuLcIzIVOXy0ukIWwaE=.sha256
